### PR TITLE
[READY] Make available for unauthenticated users

### PR DESCRIPTION
**Pull request by rosscdh**
start of patch

need the ability to have intercom available for unauthenticated users.

Thought a PR might be useful. Currently WorkInProgress

### CODE REVIEW

**Comment by kencochrane** [comment]
Thanks, let me know when it is ready for review.

**Comment by rosscdh** [comment]
Hey sorry, ran out of time. Let me know if this is still interesting, I guess its ready?

**Comment by kencochrane** [comment]
@rosscdh ok, code you have so far looks good, is there anything else? it's ready to merge?

**Comment by rosscdh** [comment]
I believe thats it! will remove WIP

**Comment by rosscdh** [comment]
Great product thanks for the review and merge!

**Comment by kencochrane** [comment]
@rosscdh thanks for the PR!

**Comment by christippett** [comment]
Hey, I noticed a bunch of 500 errors after this PR was merged. Looks like there's a regression when encoding `user_id` before hashing it for identity verification. Issue here: https://github.com/kencochrane/django-intercom/issues/27

**Comment by rosscdh** [comment]
fixed in commit https://github.com/kencochrane/django-intercom/pull/28/commits/c4a15ff7164c42696c6af8b6fd4b6101239fb542

**Pull request merged**
